repos:
  # biome linter
  -   repo: https://github.com/biomejs/pre-commit
      rev: v0.6.1  # Use the sha / tag you want to point at
      hooks:
        -   id: biome-check
            additional_dependencies: ["@biomejs/biome@1.9.4"]
  # build in prod
  -   repo: local
      hooks:
        - id: vite-build
          name: "Run Vite Build"
          entry: pnpm run build  # 或者直接 'vite build' 如果已经全局安装了 vite
          language: system     # 使用系统环境来执行命令
          types: []  # 这里可以为空，表示对所有文件都有效

  # png compress lossless
  - repo: https://github.com/shssoichiro/oxipng
    rev: v9.1.3
    hooks:
      - id: oxipng
        args: [ "-o", "4", "--strip", "safe", "--alpha" ]

  # github-action linter
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.4
    hooks:
      - id: actionlint

  # commit-repl
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.0
    hooks:
        - id: commitizen

  # commit-msg linter checker
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          - --verbose
          - --strict
          - comment
          - hotfix
          - build
          - chore
          - ci
          - docs
          - feat
          - fix
          - perf
          - refactor
          - revert
          - style
          - test