name: webpage deployment
run-name: ${{ github.actor }} webpage deployment
on:
  release:
    types: [published]


jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '8'
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build dist
        run: pnpm build && echo "success build"

      - name: SCP Upload
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          rm: true
          source: "dist"
          target: "/var/www/html"
          strip_components: 1
          script: |
            ls -al /var/www/html |
            echo "success deploy"

      - name: ssh deploy
        uses: appleboy/ssh-action@master
        with:
          command_timeout: 5m
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            whoami |
            echo "执行nginx -s reload命令" |
            echo "执行 wget www.dentistease.com" |
            echo "完成静态资源部署"
